---

- name: ensure public_keys directory exists
  file: path="public_keys" state=directory

- name: copy public key to public_keys directory for use by roles
  copy: src="{{ prelude_public_key_source }}" dest="public_keys/{{ prelude_public_key_destination_name }}"
